[package]
name = "chksound"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
id3 = "1.2.0"
mp4ameta = "0.11.0"
